/**
 * generate-action-items — port of `supabase/functions/generate-action-items`.
 *
 * Same contract: takes `{goal, researchContext, totalSteps, totalDataPoints}`
 * and returns `{actionItems: Array<{title, description, priority, timeline, ...}>}`
 * (or `{error}` on 429/402/5xx).
 *
 * Mock mode when `LOVABLE_API_KEY` unset returns 3 canned action items.
 */

import { z } from 'zod';
import { wrapUserInput } from '../_lib/sanitize';

interface ContextFinding { title: string; content: string; source?: string }
interface ContextStep { stepTitle: string; findings: ContextFinding[] }

// Schema mirrors the original Supabase function contract that
// ResearchReportModal renders against. Rich fields are optional so a
// thinned upstream LLM response still validates; the Modal also has
// defensive accessors as a second line of defense.
const ToolOutputSchema = z.object({
  actionItems: z
    .array(z.object({
      id: z.string().optional(),
      title: z.string().min(1),
      description: z.string(),
      timeline: z.string(),
      timelineDetails: z.string().optional(),
      priority: z.enum(['High', 'Medium', 'Low']),
      resources: z.object({
        budget: z.string().optional(),
        team: z.string().optional(),
        tools: z.array(z.string()).optional(),
      }).optional(),
      metrics: z.array(z.string()).optional(),
      risks: z.array(z.object({
        risk: z.string(),
        mitigation: z.string(),
      })).optional(),
      references: z.array(z.object({
        title: z.string(),
        url: z.string(),
      })).optional(),
      researchContext: z.string().optional(),
    }))
    .min(1),
  summary: z.string().optional(),
});

const SYSTEM_PROMPT =
  'You are an expert strategic planner. Generate contextual, actionable ' +
  'recommendations based on research findings. Each item must be specific, ' +
  'tied to a finding, and have a clear priority + timeline.';

const TOOL = {
  type: 'function',
  function: {
    name: 'generate_action_plan',
    description: 'Generate contextual action items + executive summary from research findings',
    parameters: {
      type: 'object',
      properties: {
        actionItems: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              id: { type: 'string' },
              title: { type: 'string' },
              description: { type: 'string' },
              timeline: { type: 'string' },
              timelineDetails: { type: 'string' },
              priority: { type: 'string', enum: ['High', 'Medium', 'Low'] },
              resources: {
                type: 'object',
                properties: {
                  budget: { type: 'string' },
                  team: { type: 'string' },
                  tools: { type: 'array', items: { type: 'string' } },
                },
              },
              metrics: { type: 'array', items: { type: 'string' } },
              risks: {
                type: 'array',
                items: {
                  type: 'object',
                  properties: {
                    risk: { type: 'string' },
                    mitigation: { type: 'string' },
                  },
                  required: ['risk', 'mitigation'],
                },
              },
              references: {
                type: 'array',
                items: {
                  type: 'object',
                  properties: {
                    title: { type: 'string' },
                    url: { type: 'string' },
                  },
                  required: ['title', 'url'],
                },
              },
              researchContext: { type: 'string' },
            },
            required: ['title', 'description', 'priority', 'timeline'],
          },
          minItems: 1,
        },
        summary: { type: 'string' },
      },
      required: ['actionItems'],
    },
  },
} as const;

export interface GenerateActionItemsRequest {
  goal: string;
  researchContext: ContextStep[];
  totalSteps: number;
  totalDataPoints: number;
}

export interface HandlerResult {
  status: number;
  body: unknown;
}

export async function generateActionItemsHandler(
  req: GenerateActionItemsRequest,
): Promise<HandlerResult> {
  const { goal, researchContext } = req;
  if (typeof goal !== 'string' || goal.trim() === '') {
    return { status: 400, body: { error: 'goal is required (string)' } };
  }

  const key = process.env.LOVABLE_API_KEY;
  if (!key) {
    const goalShort = goal.slice(0, 60);
    const mockItem = (id: string, title: string, priority: 'High' | 'Medium' | 'Low', timeline: string): unknown => ({
      id,
      title,
      description: `[mock] ${title}. This action is generated by the local-functions mock handler. Set LOVABLE_API_KEY on the functions host for real LLM responses.`,
      timeline,
      timelineDetails: `[mock] Phase breakdown for ${timeline}. Actual phase plan would come from the LLM.`,
      priority,
      resources: {
        budget: '[mock] $5,000 - $15,000',
        team: '[mock] 2-3 people: 1 lead + supporting specialists',
        tools: ['[mock] Project management tool', '[mock] Domain-specific analysis kit'],
      },
      metrics: [
        '[mock] Completion within timeline (target: 100%)',
        '[mock] Quality acceptance score (target: >4/5)',
        '[mock] Stakeholder satisfaction (target: >80%)',
      ],
      risks: [
        { risk: '[mock] Scope creep beyond initial plan', mitigation: 'Lock requirements at kickoff and use change-request process for additions.' },
        { risk: '[mock] Resource availability fluctuation', mitigation: 'Identify backup contributors and stagger critical-path work.' },
      ],
      references: [
        { title: '[mock] Strategic Planning Best Practices', url: 'https://example.invalid/mock-reference-1' },
        { title: '[mock] Implementation Playbook', url: 'https://example.invalid/mock-reference-2' },
      ],
      researchContext: `[mock] Generated from research about "${goalShort}". Real LLM response would tie this directly to specific findings.`,
    });
    return {
      status: 200,
      body: {
        actionItems: [
          mockItem('1', `[mock] Pilot quick-win for "${goalShort}"`, 'High', 'next 1-2 weeks'),
          mockItem('2', `[mock] Scale validated approach across "${goalShort}"`, 'Medium', 'next 4-8 weeks'),
          mockItem('3', `[mock] Long-term optimization for "${goalShort}"`, 'Low', 'this quarter'),
        ],
        summary: `[mock] Executive summary for "${goalShort}". The local-functions handler is in mock mode because LOVABLE_API_KEY is not set on this host. Real LLM responses would synthesize the prior research findings into a 2-3 paragraph briefing here.`,
        mock: true,
      },
    };
  }

  let summary = '';
  for (const step of researchContext ?? []) {
    summary += `\n${wrapUserInput(step.stepTitle)}:\n`;
    for (const f of step.findings ?? []) {
      summary += `• ${wrapUserInput(f.title)}: ${wrapUserInput(f.content)}\n`;
      if (f.source) summary += `  Source: ${wrapUserInput(f.source)}\n`;
    }
  }

  const userPrompt = `Research goal: ${wrapUserInput(goal)}\n\nFindings:${summary || '\n(no findings)'}\n\nGenerate prioritized action items.`;

  const upstream = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
    method: 'POST',
    headers: { Authorization: `Bearer ${key}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: 'google/gemini-2.5-flash',
      messages: [
        { role: 'system', content: SYSTEM_PROMPT },
        { role: 'user', content: userPrompt },
      ],
      tools: [TOOL],
      tool_choice: { type: 'function', function: { name: 'generate_action_plan' } },
    }),
  });

  if (!upstream.ok) {
    if (upstream.status === 429) return { status: 429, body: { error: 'Rate limits exceeded' } };
    if (upstream.status === 402) return { status: 402, body: { error: 'AI usage limit reached. Please add credits to continue.' } };
    return { status: 502, body: { error: `AI gateway error: ${upstream.status}` } };
  }

  const data = (await upstream.json()) as {
    choices?: Array<{ message?: { tool_calls?: Array<{ function?: { arguments?: string } }> } }>;
  };
  const args = data.choices?.[0]?.message?.tool_calls?.[0]?.function?.arguments;
  if (!args) return { status: 502, body: { error: 'No tool call in AI response' } };
  let raw: unknown;
  try { raw = JSON.parse(args); } catch { return { status: 502, body: { error: 'Failed to parse AI tool-call arguments' } }; }
  const validated = ToolOutputSchema.safeParse(raw);
  if (!validated.success) {
    return { status: 502, body: { error: 'AI tool-call output failed schema validation' } };
  }
  return { status: 200, body: validated.data };
}
